### ISSUE TITLE
Add License

### ISSUE THREAD

**Issue by labster** [p12tic/NativeSvgHandler#7]
Hey, I'm working with the [Miraheze wiki farm](https://meta.miraheze.org/), and we'd like to use this extension on some of our wikis.  Are we allowed to use it? Can you add some sort of FOSS license to this code?

**Comment by ricordisamoa** [comment]
At the top of NativeSvgHandler.php I read:
> This program is free software: you can redistribute it and/or modify
> it under the terms of the GNU General Public License as published by
> the Free Software Foundation, either version 2 of the License, or
> (at your option) any later version.

**Comment by labster** [comment]
Ah, I'm so stupid.  No notice on top of the i18n file, though.  Thanks.
